controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

Authors:
    path: /authors
    controller: App\Controller\AuthorController::index

Books:
    path: /books
    controller: App\Controller\BookController::index

BooksTake:
    path: /books/{id}/take
    methods: ['PATCH']
    defaults:
        _controller: App\Controller\BookController::TakeBook

BooksDepose:
    path: /books/{id}/depose
    methods: ['PATCH']
    defaults:
        _controller: App\Controller\BookController::DepositBook

Homepage:
    path: /homepage
    controller: App\Controller\HomeController::index

Movie:
    path: /Movie
    controller: App\Controller\MovieController::index

add_movie:
    path: /movie/add
    controller: App\Controller\MovieController::new

delete_movie:
    path: /movie/delete
    controller: App\Controller\MovieController::deleteMovie

UserMe:
    path: /user
    controller: App\Controller\UserController::index

UserInscription:
    path: /user/inscription
    controller: App\Controller\UserController::inscription

Login:
    path: /login
    controller: App\Controller\AppAuthenticatorController::login

Register:
    path: /register
    controller: App\Controller\RegistrationController::register
